name: ui_design
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core & Networking
  http: ^1.5.0
  uuid: ^4.5.1

  # Map & Location
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  google_maps_flutter: ^2.4.0  # ✅ moved here

  # Charts & Visualization
  fl_chart: ^1.1.0

  # UI / Layout helpers
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.2.1
  cupertino_icons: ^1.0.8

  # Appwrite backend
  appwrite: ^20.0.0

  # Chat UI
  flutter_chat_ui: ^2.9.1
  flutter_chat_types: ^3.4.4

  # Date/Time formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/temp/
    - assets/svg/

  fonts:
    - family: JetBrains
      fonts:
        - asset: assets/font/JetBrainsMono-Thin.ttf
          weight: 200
        - asset: assets/font/JetBrainsMono-Light.ttf
          weight: 300
        - asset: assets/font/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/font/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/font/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/font/JetBrainsMono-Bold.ttf
          weight: 700
